
package GUI;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


public class FAgrePaciente extends javax.swing.JFrame {

    public static final String URL = "jdbc:mysql://localhost:3306/cita";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "root";
    PreparedStatement ps;
    ResultSet rs;
    
    //Para la conexion de a la Base de Datos
    public static Connection getConection() {
        Connection conn = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            
        } catch (Exception e) {
            System.out.println(e);
        }
        return conn;
    }
    
    private void limpiarCajas() {
        //Para limpiar las cajas
        txtClave.setText(null);
        txtNombre.setText(null);
        txtApePaterno.setText(null);
        txtApeMaterno.setText(null);
        cbxGenero.setSelectedIndex(0);
        DFNacimiento.setCalendar(null);
        txtTelefono.setText(null);
        txtCorreo.setText(null);
        txtNotas.setText(null);
    }
    
    public FAgrePaciente() {
        this.getContentPane().setBackground(new Color(204, 235, 208));
        initComponents();
        setLocationRelativeTo(null);
        DFNacimiento.getJCalendar().setMaxSelectableDate(new java.util.Date());
        ((JTextFieldDateEditor)DFNacimiento.getDateEditor()).setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtClave = new java.awt.TextField();
        txtNombre = new java.awt.TextField();
        txtApePaterno = new java.awt.TextField();
        txtApeMaterno = new java.awt.TextField();
        txtTelefono = new java.awt.TextField();
        txtCorreo = new java.awt.TextField();
        txtNotas = new java.awt.TextField();
        DFNacimiento = new com.toedter.calendar.JDateChooser();
        cbxGenero = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setTitle("Informacion");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NutriappAgrePaci.png"))); // NOI18N
        jLabel1.setText("Logo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Clave");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombres");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Apellido Paterno");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Apellido Materno");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Telefono");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Correo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Genero");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Fecha de nacimiento");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Notas");

        txtClave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtApePaterno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtApeMaterno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtNotas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        DFNacimiento.setDateFormatString("dd/MM/yyyy");
        DFNacimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbxGenero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Masculino", "Femenino" }));

        btnModificar.setBackground(new java.awt.Color(148, 185, 185));
        btnModificar.setText("Modifcar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(148, 185, 185));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(148, 185, 185));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(148, 185, 185));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(148, 185, 185));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtApePaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApeMaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, 167, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnGuardar)
                        .addGap(34, 34, 34)
                        .addComponent(btnModificar)
                        .addGap(30, 30, 30)
                        .addComponent(btnLimpiar)
                        .addGap(45, 45, 45)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(DFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel9)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Connection con = null;
        java.util.Date date = DFNacimiento.getDate();
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);
        try {
            if("".equals(txtClave.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar la Clave");
                return;
            }
            if("".equals(txtNombre.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Nombre");
                return;
            }
            if("".equals(txtApePaterno.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Apellido Paterno");
                return;
            }
            if("".equals(txtApeMaterno.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Apellido Materno");
                return;
            }
            if(cbxGenero.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Falta seleccionar el Genero");
                return;
            }
            if("".equals(txtTelefono.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Telefono");
                return;
            }
            if("".equals(txtCorreo.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Correo");
                return;
            }
            con = getConection();
            ps = con.prepareStatement("UPDATE paciente SET Nombre=?, Apellido_paterno=?, Apellido_materno=?, Genero=?, Fecha_nacimiento=?, Telefono=?, Correo=?, Notas=? WHERE Clave=?");
            ps.setString(9, txtClave.getText());
            ps.setString(1, txtNombre.getText());
            ps.setString(2, txtApePaterno.getText());
            ps.setString(3, txtApeMaterno.getText());
            ps.setString(4, cbxGenero.getSelectedItem().toString());
            ps.setDate(5, fecha);
            ps.setString(6, txtTelefono.getText());
            ps.setString(7, txtCorreo.getText());
            ps.setString(8, txtNotas.getText());

            int res = ps.executeUpdate(); 
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Informacion actualizada");
                limpiarCajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar informacion");
                limpiarCajas();
            }
            con.close();
            
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar paciente");
            System.err.println(e);
            
                limpiarCajas();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Connection con = null;
        java.util.Date date = DFNacimiento.getDate();
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);
        try {
            if("".equals(txtClave.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar la Clave");
                return;
            }
            if("".equals(txtNombre.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Nombre");
                return;
            }
            if("".equals(txtApePaterno.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Apellido Paterno");
                return;
            }
            if("".equals(txtApeMaterno.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Apellido Materno");
                return;
            }
            if(cbxGenero.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Falta seleccionar el Genero");
                return;
            }
            if("".equals(txtTelefono.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Telefono");
                return;
            }
            if("".equals(txtCorreo.getText())){
                JOptionPane.showMessageDialog(null, "Falta ingresar el Correo");
                return;
            }
            con = getConection();
            ps = con.prepareStatement("INSERT INTO paciente (Clave, Nombre, Apellido_paterno, Apellido_materno, Genero, Fecha_nacimiento, Telefono, Correo, Notas) VALUES(?,?,?,?,?,?,?,?,?)");
            ps.setString(1, txtClave.getText());
            ps.setString(2, txtNombre.getText());
            ps.setString(3, txtApePaterno.getText());
            ps.setString(4, txtApeMaterno.getText());
            ps.setString(5, cbxGenero.getSelectedItem().toString());
            ps.setDate(6, fecha);
            ps.setString(7, txtTelefono.getText());
            ps.setString(8, txtCorreo.getText());
            ps.setString(9, txtNotas.getText());

            int res = ps.executeUpdate(); 
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Paciente Guardada");
                limpiarCajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar paciente");
                limpiarCajas();
            }
            con.close();
            
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar paciente");
            System.err.println(e);
            
                limpiarCajas();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCajas();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        limpiarCajas();
        this.setVisible(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Connection con = null;
        try {
            con = getConection();
            ps = con.prepareStatement("SELECT * FROM paciente WHERE clave = ?");
            ps.setString(1, txtClave.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                txtNombre.setText(rs.getString("Nombre"));
                txtApePaterno.setText(rs.getString("Apellido_paterno"));
                txtApeMaterno.setText(rs.getString("Apellido_materno"));
                cbxGenero.setSelectedItem(rs.getString("Genero"));
                Date aux = rs.getDate("Fecha_nacimiento");
                DFNacimiento.setDate(aux);
                txtTelefono.setText(rs.getString("Telefono"));
                txtCorreo.setText(rs.getString("Correo"));
                txtNotas.setText(rs.getString("Notas"));
            } else {
                JOptionPane.showMessageDialog(null, "No existe registro con esa clave");
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAgrePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAgrePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAgrePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAgrePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAgrePaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DFNacimiento;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.TextField txtApeMaterno;
    private java.awt.TextField txtApePaterno;
    private java.awt.TextField txtClave;
    private java.awt.TextField txtCorreo;
    private java.awt.TextField txtNombre;
    private java.awt.TextField txtNotas;
    private java.awt.TextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
